/**
 * Syllabus-derived topic taxonomy for the Notes module Topic Selector.
 *
 * topics.json is generated by scripts/derive-topics.ts from the official CAIE
 * syllabus PDFs in knowledge-base-source — regenerate it after a syllabus
 * update instead of editing by hand (rules.md forbids authored CAIE content).
 */

import topicsData from "./topics.json";
import type { SubjectId } from "@/lib/subjects";

export interface TopicOption {
  id: string;
  title: string;
  /**
   * Optional grouping label used by the selector to render category headers.
   * Populated for the granular sub-topic map (see kb/subtopics.ts); undefined
   * for the flat, syllabus-derived topics.json entries.
   */
  group?: string;
}

export interface PaperOption {
  id: string;
  title: string;
  topics: TopicOption[];
}

export interface SubjectTaxonomy {
  syllabus_file: string;
  papers: PaperOption[];
}

const TAXONOMIES = topicsData as Record<string, SubjectTaxonomy>;

export function getTopicTaxonomy(
  subject: SubjectId
): SubjectTaxonomy | undefined {
  return TAXONOMIES[subject];
}

/**
 * Topic choices for the selector: topics of one paper, or the de-duplicated
 * union across all papers when "all papers" is selected.
 */
export function getTopicOptions(
  taxonomy: SubjectTaxonomy,
  paperId: string
): TopicOption[] {
  if (paperId !== "all") {
    return taxonomy.papers.find((paper) => paper.id === paperId)?.topics ?? [];
  }
  const seen = new Set<string>();
  const union: TopicOption[] = [];
  for (const paper of taxonomy.papers) {
    for (const topic of paper.topics) {
      if (!seen.has(topic.title)) {
        seen.add(topic.title);
        union.push(topic);
      }
    }
  }
  return union;
}
